"""added candidate fields to ServiceContract

Revision ID: 2e0d94506cd5
Revises: b0f3fa83a775
Create Date: 2025-07-26 14:51:09.906438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e0d94506cd5'
down_revision = 'b0f3fa83a775'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_contract', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requirementid', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('candidateid', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('placementid', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('candidatename', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('candidateaddress', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('candidateemail', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('candidatephone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('candidateltdname', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('candidateltdregno', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_contract', schema=None) as batch_op:
        batch_op.drop_column('candidateltdregno')
        batch_op.drop_column('candidateltdname')
        batch_op.drop_column('candidatephone')
        batch_op.drop_column('candidateemail')
        batch_op.drop_column('candidateaddress')
        batch_op.drop_column('candidatename')
        batch_op.drop_column('placementid')
        batch_op.drop_column('candidateid')
        batch_op.drop_column('requirementid')

    # ### end Alembic commands ###
