"""added jurisdiction and corrected job title

Revision ID: 377cf487eea3
Revises: ae8261e6c66c
Create Date: 2025-08-05 20:12:04.928324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '377cf487eea3'
down_revision = 'ae8261e6c66c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_contract', schema=None) as batch_op:
        batch_op.add_column(sa.Column('companyjurisdiction', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('candidatejurisdiction', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_contract', schema=None) as batch_op:
        batch_op.drop_column('candidatejurisdiction')
        batch_op.drop_column('companyjurisdiction')

    # ### end Alembic commands ###
