"""added jobtitle

Revision ID: 42c81abfed93
Revises: 2e0d94506cd5
Create Date: 2025-07-29 16:11:38.905012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42c81abfed93'
down_revision = '2e0d94506cd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_contract', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jobtitle', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_contract', schema=None) as batch_op:
        batch_op.drop_column('jobtitle')

    # ### end Alembic commands ###
