"""added candidate surname for searches

Revision ID: 93c5bb4496a1
Revises: 377cf487eea3
Create Date: 2025-08-06 08:20:39.499749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93c5bb4496a1'
down_revision = '377cf487eea3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_contract', schema=None) as batch_op:
        batch_op.add_column(sa.Column('candidatesurname', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_contract', schema=None) as batch_op:
        batch_op.drop_column('candidatesurname')

    # ### end Alembic commands ###
