"""initial

Revision ID: b0f3fa83a775
Revises: 
Create Date: 2025-07-24 14:21:25.831264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0f3fa83a775'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_arrangement',
    sa.Column('service_arrangement_id', sa.Integer(), nullable=False),
    sa.Column('sid', sa.String(length=10), nullable=True),
    sa.Column('day', sa.String(length=10), nullable=True),
    sa.Column('defaultserviceperiod', sa.String(length=255), nullable=True),
    sa.Column('atservicebase', sa.String(length=255), nullable=True),
    sa.Column('atclientlocation', sa.String(length=255), nullable=True),
    sa.Column('atotherlocation', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('service_arrangement_id')
    )
    op.create_table('service_contract',
    sa.Column('service_contract_id', sa.Integer(), nullable=False),
    sa.Column('sid', sa.String(length=10), nullable=True),
    sa.Column('servicename', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('startdate', sa.Date(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('durationunit', sa.String(length=10), nullable=True),
    sa.Column('enddate', sa.Date(), nullable=True),
    sa.Column('companyid', sa.Integer(), nullable=True),
    sa.Column('companyname', sa.String(length=255), nullable=True),
    sa.Column('companyregistrationnumber', sa.String(length=50), nullable=True),
    sa.Column('companyaddress', sa.String(length=255), nullable=True),
    sa.Column('companyphone', sa.String(length=50), nullable=True),
    sa.Column('companyemail', sa.String(length=100), nullable=True),
    sa.Column('contactid', sa.Integer(), nullable=True),
    sa.Column('contactname', sa.String(length=100), nullable=True),
    sa.Column('contacttitle', sa.String(length=50), nullable=True),
    sa.Column('contactemail', sa.String(length=100), nullable=True),
    sa.Column('contactphone', sa.String(length=50), nullable=True),
    sa.Column('contactaddress', sa.String(length=255), nullable=True),
    sa.Column('dmname', sa.String(length=100), nullable=True),
    sa.Column('dmtitle', sa.String(length=50), nullable=True),
    sa.Column('dmemail', sa.String(length=100), nullable=True),
    sa.Column('dmphone', sa.String(length=50), nullable=True),
    sa.Column('specialconditions', sa.Text(), nullable=True),
    sa.Column('noticeperiod', sa.Integer(), nullable=True),
    sa.Column('noticeperiod_unit', sa.String(length=10), nullable=True),
    sa.Column('fees', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('feecurrency', sa.String(length=3), nullable=True),
    sa.Column('charges', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('chargecurrency', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('service_contract_id')
    )
    op.create_table('service_standard',
    sa.Column('service_standard_id', sa.Integer(), nullable=False),
    sa.Column('sid', sa.String(length=10), nullable=True),
    sa.Column('ssn', sa.String(length=10), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('service_standard_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_standard')
    op.drop_table('service_contract')
    op.drop_table('service_arrangement')
    # ### end Alembic commands ###
